
services:
  vault:
    image: hashicorp/vault:1.19
    container_name: vault_dev
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDRESS: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    volumes:
      - vault_data:/vault/data
    command: vault server -dev -dev-listen-address=0.0.0.0:8200
volumes:
  vault_data: